CREATE TEMPORARY TABLE CUSTOMER_ORDERS_TEMP AS
SELECT
	ORDER_ID,
	CUSTOMER_ID,
	PIZZA_ID,
	CASE
		WHEN EXCLUSIONS IS NULL OR EXCLUSIONS LIKE 'null' THEN ' '
		ELSE EXCLUSIONS
		END AS EXCLUSIONS,
	CASE
		WHEN EXTRAS IS NULL OR EXTRAS LIKE 'null' THEN ' '
		ELSE EXTRAS
		END AS EXTRAS,
	ORDER_TIME
FROM CUSTOMER_ORDERS

SELECT * FROM RUNNER_ORDERS
CREATE TEMPORARY TABLE RUNNER_ORDERS_TEMP AS
SELECT
	ORDER_ID,
	RUNNER_ID,
	CASE
		WHEN PICKUP_TIME LIKE 'null' THEN ' '
		ELSE PICKUP_TIME
		END AS PICKUP_TIME,
	CASE
		WHEN DISTANCE LIKE 'null' THEN ' '
		WHEN DISTANCE LIKE '%km' THEN TRIM('km' FROM DISTANCE)
		ELSE DISTANCE
		END AS "distance(km)",
	CASE
		WHEN DURATION LIKE 'null' THEN ' '
		WHEN DURATION LIKE '%minutes' THEN TRIM('minutes' FROM DURATION)
		WHEN DURATION LIKE '%mins' THEN TRIM('mins' FROM DURATION)
		WHEN DURATION LIKE '%minute' THEN TRIM('minute' FROM DURATION)
		ELSE DURATION
		END AS "duration(mins)",
	CASE
		WHEN CANCELLATION IS NULL OR CANCELLATION LIKE 'null' THEN ' '
		ELSE CANCELLATION
		END AS CANCELLATION
FROM RUNNER_ORDERS
DROP TABLE IF EXISTS RUNNER_ORDERS_TEMP;