-- 1. How many pizzas were ordered?
SELECT COUNT(*) AS PIZZA_ORDERS
FROM CUSTOMER_ORDERS

-- 2. How many unique customer orders were made?
SELECT COUNT(DISTINCT CUSTOMER_ID) AS UNIQUE_CUSTOMERS
FROM CUSTOMER_ORDERS

-- 3. How many successful orders were delivered by each runner?
SELECT 
	RUNNER_ID, 
	COUNT(ORDER_ID)
FROM RUNNER_ORDERS
WHERE PICKUP_TIME<>'null'
GROUP BY 1
ORDER BY 1

-- How many of each type of pizza was delivered?
SELECT
	PIZZA_NAME,
	COUNT(CO.PIZZA_ID) AS NUMBER_OF_PIZZAS
FROM 
	PIZZA_NAMES AS PN JOIN CUSTOMER_ORDERS CO
	ON PN.PIZZA_ID = CO.PIZZA_ID
	JOIN RUNNER_ORDERS AS RO
	ON CO.ORDER_ID = RO.ORDER_ID
WHERE PICKUP_TIME<>'null'
GROUP BY 1
-- How many Vegetarian and Meatlovers were ordered by each customer?
SELECT
	PIZZA_NAME,
	CUSTOMER_ID,
	COUNT(CO.PIZZA_ID) AS NUMBER_OF_PIZZAS
FROM 
	PIZZA_NAMES AS PN JOIN CUSTOMER_ORDERS CO
	ON PN.PIZZA_ID = CO.PIZZA_ID
	JOIN RUNNER_ORDERS AS RO
	ON CO.ORDER_ID = RO.ORDER_ID
WHERE PICKUP_TIME<>'null'
GROUP BY 1, 2
ORDER BY 1, 2

-- What was the maximum number of pizzas delivered in a single order?
SELECT 
	RO.ORDER_ID,
	COUNT(PIZZA_ID) AS NUMBER_OF_PIZZAS
FROM 
	RUNNER_ORDERS AS RO JOIN CUSTOMER_ORDERS AS CO
	ON RO.ORDER_ID = CO.ORDER_ID
WHERE PICKUP_TIME<>'null'
GROUP BY 1
ORDER BY 2 DESC
LIMIT 1

-- For each customer, how many delivered pizzas had at least 1 change and how many had no changes?
SELECT 
	CUSTOMER_ID,
	SUM(CASE
			WHEN EXCLUSIONS <> ' ' AND EXTRAS <> ' ' THEN 1
			ELSE 0
		END) AS CHANGE,
	SUM(CASE
	   		WHEN EXCLUSIONS = ' ' AND EXTRAS = ' ' THEN 1
	   		ELSE 0
	    END) AS NO_CHANGE
FROM 
	CUSTOMER_ORDERS_TEMP AS CO JOIN RUNNER_ORDERS AS RO 
	ON CO.ORDER_ID = RO.ORDER_ID
WHERE PICKUP_TIME<>'null'
GROUP BY 1
-- How many pizzas were delivered that had both exclusions and extras?
SELECT 
	COUNT(PIZZA_ID) AS PIZZA_DELIVERED_W_EXCLUESIONS_AND_EXTRAS
FROM 
	CUSTOMER_ORDERS_TEMP AS CO JOIN RUNNER_ORDERS AS RO 
	ON CO.ORDER_ID = RO.ORDER_ID
WHERE 
	PICKUP_TIME<>'null'
	AND EXCLUSIONS <> ' '
	AND EXCLUSIONS IS NOT NULL
	AND EXTRAS <> ' '
	AND EXTRAS IS NOT NULL
-- What was the total volume of pizzas ordered for each hour of the day?
SELECT
	EXTRACT(HOUR FROM ORDER_TIME) AS HOUR,
	COUNT(PIZZA_ID) NUMBER_OF_PIZZAS
FROM 
	CUSTOMER_ORDERS
GROUP BY 1
ORDER BY 1
-- What was the volume of orders for each day of the week?
SELECT 
	TO_CHAR(ORDER_TIME, 'Day') AS DAY_OF_WEEK,
	COUNT(ORDER_ID) AS NUMBER_OF_ORDERS
FROM CUSTOMER_ORDERS
GROUP BY 1
ORDER BY 2